### ISSUE TITLE
Cant' Authenticate with Garming

### ISSUE THREAD

**Issue by skovalenko-github** [flackdl/ifit-garmin-sync#8]
I am trying to start using the ifit synch again, deployed on Heroku, after a summer break, and I am getting  Unable to Authenticate with Garmin - I checked the username and password, they have not changed since the last time I was able to use it successfully, and I can still authenticate with this credentials directly on Gramin Connect website. Any idea what could be wrong?

`2021-11-24 16:43:12,766 [CRITICAL] Login Failure: Authentification failed.
2021-11-24T16:43:12.767055+00:00 app[worker.1]: [2021-11-24 16:43:12,766: CRITICAL/ForkPoolWorker-8] Login Failure: Authentification failed.
2021-11-24T16:43:12.769478+00:00 app[worker.1]: [2021-11-24 16:43:12,769: ERROR/ForkPoolWorker-8] could not authenticate with garmin
2021-11-24T16:43:12.770298+00:00 app[worker.1]: [2021-11-24 16:43:12,769: ERROR/ForkPoolWorker-8] Task sync.tasks.sync[8c55ed56-3e34-42d6-8076-a222df16ff94] raised unexpected: Exception('could not authenticate with garmin',)
2021-11-24T16:43:12.770299+00:00 app[worker.1]: Traceback (most recent call last):
2021-11-24T16:43:12.770300+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 405, in trace_task
2021-11-24T16:43:12.770300+00:00 app[worker.1]:     R = retval = fun(*args, **kwargs)
2021-11-24T16:43:12.770300+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/celery/app/trace.py", line 697, in __protected_call__
2021-11-24T16:43:12.770301+00:00 app[worker.1]:     return self.run(*args, **kwargs)
2021-11-24T16:43:12.770301+00:00 app[worker.1]:   File "/app/src/sync/tasks.py", line 17, in sync
2021-11-24T16:43:12.770302+00:00 app[worker.1]:     return processor.process()
2021-11-24T16:43:12.770302+00:00 app[worker.1]:   File "/app/src/sync/processor.py", line 47, in process
2021-11-24T16:43:12.770303+00:00 app[worker.1]:     self._import(paths_exported)
2021-11-24T16:43:12.770303+00:00 app[worker.1]:   File "/app/src/sync/processor.py", line 77, in _import
2021-11-24T16:43:12.770303+00:00 app[worker.1]:     raise Exception('could not authenticate with garmin')
2021-11-24T16:43:12.770307+00:00 app[worker.1]: Exception: could not authenticate with garmin`

**Comment by flackdl** [comment]
This app may not be necessary anymore.  My wife told me the iFit app now lets you sync directly to Garmin and Strava.  Let me know if you can confirm the same feature.

**Comment by skovalenko-github** [comment]
Unfortunately it would only import the activities recorded in Garmin into the iFit app, but it won't send the iFit runs to Garmin, which is what I need and what this app used to do well for me.

**Comment by flackdl** [comment]
Ah, you're right.  It's not bidirectional from the iFit app.

And I can confirm I experience that same authentication issue.  I just [made an update](https://github.com/flackdl/ifit-garmin-sync/commit/930394f41122f864f409dbe4c533bae4f38cc863) which seemed to fix the authentication issues.  I upgraded the dependency https://github.com/La0/garmin-uploader to version `1.0.10` and my workouts sync successfully.  Redeploy your app and let me know.

**Comment by skovalenko-github** [comment]
Thank you so much! It totally fixed it!
PS. Sorry for the delayed response.
